### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by 122christo** [dangrie158/EEPROgraMmer#1]
I got a syntaxError:

XXXr$ eepro --h
Traceback (most recent call last):
  File "/home/christoph/.local/bin/eepro", line 5, in <module>
    from eepro.eepro import main
  File "/home/christoph/.local/lib/python3.5/site-packages/eepro/eepro.py", line 63
    return f"fill bytes (0x{self.fill_byte[0]:02X})"
                                                   ^
SyntaxError: invalid syntax

How to fix it?

**Comment by dangrie158** [comment]
Hi, you are using python 3.5. The project uses f-Strings which were introduced in 3.6.

Upgrade to at least this version and it should work 😊

Alternatively you could modify the code to use old style string formatting. I think this is really the only dependency on 3.6

**Comment by 122christo** [comment]
OK, your software needs python 3.6. This can create problems if you use Ubuntu. (Ubuntu depends heavily on python and some versions use python3.5. and they hate python3.6) In this case you need python3.6 only for this software. I run in this problem. The solution is to create a virtual environment. 
Just type: virtualenv venv -p python3.6 after you installed all the necessary stuff.
after this eepro -- ... should work.
