### ISSUE TITLE
Adresses not changing with write

### ISSUE THREAD

**Issue by 122christo** [dangrie158/EEPROgraMmer#2]
I've put some LEDs at the adresslines for debugging. If I "read" I see the LEDs funny blinking. If I try to "write" I see no blinking. So writing dosn't work.

**Comment by dangrie158** [comment]
What’s the output on the terminal? Is it hanging or does it exit with an error?

**Comment by 122christo** [comment]
I must apologize for my impatience. Yesterday evening it dosn't work, now it does. Why? Nobody knows. I've changed nothing. Maybe the reboot?
